Repository robot-lab/judyst-main-web-service, pull requests merged in 2018-11, with the labels that each got.

#118 add views for search !new!
  celery/__init__.py
  celery/celery_app.py
  celery/data.py
  celery/data_utils.py
  core/models.py
  core/serializers.py
  core/tests/links_example.json
  core/tests/test_models/test_links_model.py
  core/tests/test_utils/test_link_utils.py
  core/tests/test_views/search_view_set/test_views_search.py
  core/urls/search_urls.py
  core/utils/functions.py
  core/views.py
  judyst_web_service/settings.py
Labels: area/rest-api, priority/top, type/feature, type/task

#132 Исправлены 500 ошибки на 400
  core/views.py
Labels: area/rest-api, priority/normal, type/bug

#136 Выдача документа по редакции
  core/serializers.py
  core/utils/functions.py
  core/views.py
Labels: area/rest-api, priority/high, type/task
