Repository robot-lab/judyst-main-web-service, pull requests merged in 2018-10, with the labels that each got.

#29 task-28
  judyst_web_service/__init__.py
  judyst_web_service/settings.py
  judyst_web_service/urls.py
  judyst_web_service/wsgi.py
  manage.py
  requirements.txt
Labels: feature, priority 1, task

#31 Add configuration for travis
  .travis.yml
  README.md
Labels: feature, priority 1, task

#107 Первоначальная настройка Travis CI и логика работы с пользователями
  .bandit
  .travis.yml
  Dockerfile
  README.md
  conf.json
  core/__init__.py
  core/admin.py
  core/apps.py
  core/forms.py
  core/migrations/__init__.py
  core/models.py
  core/serializers.py
  core/tests/__init__.py
  core/tests/test_exceptions.py
  core/tests/test_models.py
  core/tests/test_utils.py
  core/tests/test_views.py
  core/tests/utils.py
  core/urls/__init__.py
  core/urls/search_urls.py
  core/urls/user_urls.py
  core/utils/__init__.py
  core/utils/decorators.py
  core/utils/exceptions.py
  core/utils/functions.py
  core/views.py
  docker-cloud.yml
  docker-compose.yml
  judyst_web_service/settings.py
  judyst_web_service/urls.py
  pytest.ini
  requirements.txt
  start.sh
  travis_conf.json
Labels: area/rest-api, priority/top

#110 Представление поиска ссылок
  core/admin.py
  core/models.py
  core/serializers.py
  core/tests/links_example.json
  core/tests/test_models.py
  core/tests/test_utils.py
  core/tests/test_views.py
  core/tests/utils.py
  core/urls/search_urls.py
  core/urls/user_urls.py
  core/utils/functions.py
  core/views.py
Labels: area/rest-api, priority/top, type/feature
